services:
  database:
    image: postgres:14-alpine

    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ocelot

    volumes:
       - ./init:/docker-entrypoint-initdb.d
       - postgres_data:/var/lib/postgresql/data

  backend:
    build:
        context: ./ocelot-backend
        dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./ocelot-backend:/app
      - /app/node_modules
    working_dir: /app

    depends_on:
      - database

  frontend:
    build:
        context: ./ocelot
        dockerfile: Dockerfile 
    ports:
    - "8080:80"
    - "19000:19000"
    - "19001:19001"
    - "19002:19002"
    - "8081:8081"   
    volumes:
     - ./ocelot:/app
     - /app/node_modules
    working_dir: /app
    depends_on:
        - backend

volumes:
  postgres_data:
    driver: local